---
title: "The Animal Farm"
url: "/the_animal_farm"
book_authors: ["George Orwell"]
book_isbn: 978-1-943138-42-5
book_started_date: 2016-12-10
book_finished_date: 2016-12-10
book_rating: 5
book_year: 1945
subtitle: 
date: 2016-12-26
lastmod: 2018-03-16
draft: false
acknowledgement: 
categories: ["Readings"]
type: reading
tags: []
people: []
places: []
locations: ["San Francisco"]
---

= The Animal Farm
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-03-16
:docdate: 2018-03-16

A comprehensive history of Russian revolution in a short, simple book that anyone can understand. 
I think in this fact lies the beauty of Orwell’s work. 
People of all ages can appreciate and visualize even the most complex social changes.

It seems that Orwell did describe Russian revolution very closely with fall of the capitalist empire, communist revolution, Marx, collectivization, fight between Trotsky and Stalin, dictatorship and full counter-revolution and come back to the similar state as it was before 1917 but with a different name.

Also, it seems, that even if it accounts for the Russian revolution, 
the pattern is the same for all them. 
This book is a reminder to us how events usually unfold and what happens at the end. 
And what kind of people typically end-up on top in any system regarding of the title.
