---
title: "What I Talk About When I Talk About Running"
url: "/what_i_talk_about_when_i_talk_about_running"
book_authors: ["Haruki Murakami"]
book_isbn: 978-0-307-38983-1
book_started_date: 2016-10-17
book_finished_date: 2016-10-17
book_rating: 5
book_year: 2008
book_pages: 194
subtitle: 
date: 2016-10-19
lastmod: 2018-09-29
draft: false
acknowledgement: 
categories: ["Readings"]
type: reading
tags: ["running"]
people: []
places: []
locations: ["San Francisco"]
---

= What I Talk About When I Talk About Running
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-09-29
:docdate: 2017-05-28
:nofooter:
:document_type: reading
:tags: ""

Very personal memoir by Haruki Murakami that covers 30 something years of his life: after he became a writer and started to run.

Few interesting things that I noticed:

 - Murakami shows his struggles with getting older. Aging is such an important topic that touches everyone often not talked about. Seeing your result getting worth with age is a good way to be aware of time in life. It keeps you focused on the crucial thing and helped you appreciate life.
 
 - I appreciated how he put the duration of human life in a better perspective. He became a writer after being 33 years old. He sold his bar, quit smoking, changed his diet, started writing and running. The best part of the life for him began after he became true to himself in the mid-30s.
 
 - Murakami emphasizes how for him life is the process of knowing himself better. Knowing what he likes, what is crucial for him. His focus is on internal matters and not external things. He decides to spend as much time with people he likes and avoid people he dislikes. He is not competitive because for him competitiveness is about looking outward not inward.

 - Another valuable lesson: everything worthy in life requires a big effort. He shows how setting up routine and rules for himself was paramount.
