---
title: "Ми"
url: "/my"
aliases: []
description: "Про нас"
date: 2018-03-26
lastmod: 2018-04-23
draft: false
acknowledgement: 
categories: ["Розмови"]
tags: ["poem", "поезія", "людино", "розмови"]
people: []
places: []
locations: ["San Francisco"]
---

= Ми
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-03-26
:docdate: 2018-03-26
:nofooter:
:document_type: rozmovy

Ти не гірше. +
Ти не краще. +
Навіщо ці порівняння? +
Ми всі рівні. +
Ми всі брати. +
Ми всі сестри. +

Чому ми такі жорстокі? +
Де поділась наша людяність? +
Ти думаєш справа у світі? +
У справедливості? +

Але так було завджи, +
І так буде завжди. +
І люди були людьми в часи голокосту та воєн. +
Чому ми не можемо так? +

Ми можемо. +
Ми нащадки справжніх людей. +
Ми їх продовження. +
І хтось буде продовженням нас. +

Ми в цьому разом. +
Ми ланка єдиного ланцюгу. +
Ми поєднуємо покоління. +

Без них не було минулого. +
Без нас не буде майбутнього. +

Чому ми жаліємось? +
Про що нам жалітись? +
Якщо вони змогли, то зможемо і ми. +
Чи не задля цього нам треба жити? +

Хіба усмішка дитини,  +
Хіба сльоза друга +
Не варті наших зусиль? +
Хіба вони не варті подолання нашого страху? +

Ми маленькі частинки людства та всесвіту +
Але ми є їх невідємними частинами +
Без нас нічого не буде. +
Наша хоробрість, наша любов врятують все. +
