---
title: "Не втікай"
url: "/ne-vtikai"
aliases: []
description: "Про віру"
date: 2018-03-25
lastmod: 2018-09-29
draft: false
acknowledgement: 
categories: ["Розмови"]
tags: ["poem", "поезія", "людино", "розмови"]
people: []
places: []
locations: ["San Francisco"]
---

= Не втікай
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-03-25
:docdate: 2018-09-29
:nofooter:
:document_type: rozmovy


Не втікай, +
              Я теж боюсь. +
Не біжи, +
             Я теж соромлюсь. +

Зупинись. Подивись. +

В твоєму страсі я бачу свій страх. +
В твоєму обличчі я бачу себе. +
В твоїх проблемах я бачу свої проблеми. +
В твоєму соромі я бачу свій сором. +
В твоєму болі я бачу свій біль. +

Не біжи, +
             Я теж боюсь. +
Зупинись. Подивись. +

Я хочу обняти тебе. +
Я хочу щоб ти обняла мене. +
Я хочу багато сказати тобі. +
Але я соромлюсь себе. +
І боюсь не сподобатись тобі. +
Я боюсь не бути тим, ким ти мене бачиш. +
Я боюсь бути не гідним тебе. +
Мені страшно, так само як і тобі. +

Мені болить, що тобі болить. +
В твоїх очах мої очі. +
В твоїй сумній усмішці - я. +
Твоя ображена дитина - це також я. +

Вдвох не так страшно - повір мені. +
Ми не ідеальні, у нас багато проблем, +
Тому що ми - живі, +
Ми - люди. Живі люди. +

Ми можемо сміятись,  +
Але ми сумуємо. +
Ми можемо виглядати сильними і дорослими, +
Але ми слабкі, беззахисні, ображені діти. +

Не біжи. Благаю, не поспішай. +
Ми завжди це встигнемо. +
Якщо є 1 відсоток шансу, то треба пробувати. +
Це коштує всього болю та всіх сліз. +

Ми далеко, але не поспішай, зупинись.