---
title: "Вразливість"
url: "/vrazlyvist"
aliases: []
description: "Про вразливість"
date: 2018-04-22
lastmod: 2018-04-23
draft: false
acknowledgement: 
categories: ["Розмови"]
tags: ["poem", "поезія", "вразливість", "розмови"]
people: []
places: []
locations: ["Kyiv-Lviv, Ukraine"]
---

= Вразливість
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-04-22
:docdate: 2018-04-22    

Будь вразливим. +
Виглядати сильним може кожен. +
Але сила розділяє нас. +
Будь вразливим. +
Це об’єднує. +

У всіх є проблеми, +
Страхи, недоліки, +
Дитячі травми, +
Образи, трагедії та помилки дорослого життя. +

Сила ізолює тебе. +
Залишає тебе наодинці з усім цим. +
Будь вразливим. +
Тобі буде легше. +

Показуй свою слабкість людям. +
Показуй свіх біль. Показуй свої сльози. +
Цe змінить усе. +
Прийде легкісь та теплота. +

Ми розуміємо один одного + 
Не через досягнення. +
Ми розуміємо один одного +
Через страхи та біль. +
Ділись цим +
І все відкриється. +
З’являться усмішки добра + 
Та сльози легкості. +

Будь вразливим. +
Це і є бути людиною. +
Ми не машини, ми не роботи. +
Ми зламані діти + 
Зі шрамами від дорослого життя. +
Але в цьому наша чарівність, наша людяність. +
