---
title: "Ти"
url: "/ty"
aliases: []
description: "Ти і слова, слова і ти"
date: 2019-01-05
lastmod: 2019-02-01
draft: false
acknowledgement: 
categories: ["Розмови"]
tags: ["poem", "поезія", "людино", "розмови"]
people: []
places: []
locations: ["Paris", "San Francisco"]
---

= Ти

Ти не знаєш що слово значить +
Але використовуєш його все одно +
Ти не знаєш що слово ранить +
Опускає людину на дно +

Ти не думаєш про наслідки +
Для тебе слова, як і дії, пусті +
Ти не віриш що інші страждають +
Ти не знаєш що серця крихкі +

Ти говориш великими фразами +
Ти думаєш що розумніша за всіх +
Як же сильно ти помиляєшся +
Ти несеш страждання для них +

'''

Ти не вмієш творити любов +
Хоча багато про це говориш +
Ти не можеш прийняти себе +
Тому іншу людину довбиш +

Ти не можеш знайти спокій +
Бо ти обманула себе +
Лише насолода без цінностей +
Ніколи не звільнить тебе +

Ти не вмієш вибачатись +
Тому що ти не любиш себе +
А поки себе не полюбиш +
Не зможуть любити тебе +

Ти не вмієш співчувати +
Тому що ти заблокувала біль +
Перестань себе аналізувати +
І любов прийде звідусіль +

'''

Пробач себе +
Позбудься жалю + 
Позбудься відчуття вини +
Люби себе +
Тебе пробачать +
І зможеш далі ти іти +

Борися з егом - ти звичайна +
Не розумніша ти, повір +
Повіриш, зможеш ти збагнути +
І жити знову як колись +

Слова не варті нічого +
Вчинки визначають все +
Слова можуть вбити +
Вчинки зцілити тебе +

Забудь що ти хотіла сказати +
Не варто це витрати сил +
Зроби що повинна зробити + 
Відчуй любові в серці прилив + 
