---
title: "Farewell"
url: "/farewell"
aliases: []
description: "A short farewell"
date: 2018-02-21
lastmod: 2018-03-14
draft: false
acknowledgement:
categories: ["Poems"]
tags: ["poem", "poetry", "farewell"]
people: []
places: []
locations: ["San Francisco"]
---

= A Little Prayer
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-03-14
:docdate: 2018-02-10
:nofooter:
:document_type: poem

Hey, why did you do it that way? +
Why did you have need to betray? +
You wanted out, and you wanted to be free +
Why not just ask, why needed you to flee? +

Why did you blame me for all the things? +
Why did you cut your own wings? +
Why didn’t you just stand by me? +
Why did you kill a kid in me? +
 +

You wanted drugs, and sex, and love, +
You wanted all those things above +
And what about trust my dear? +
It is indeed is super rare. +

You hide your wishes by the lie +
And no, no, no - you can’t deny +
You didn’t give a single try +
You made me cry, you made me cry. +

How can you be so ruthless, dear? +
How did forget you all that fear? +
That was denying you to live +
I stood by you, I was your peer. +

I trust you made correct decision, +
You liberated self, I wish you well +
I will not be sad, and I will not dwell +
The life will not stop for me as well. +

Enjoy, my dear, your new freedom. +
Enjoy it, cause I paid the price. +
Avoid the sadness and the boredom. +
I’ve paid for it exactly twice. +

Of course, of course, you are not a devil, +
But you did hit me in the middle of the heart, +
Of course, that wasn’t purely evil +
But you did tear myself apart. +

There is not much left to say, +
All I can do is pray, pray, pray. +
Pray for my heart, my strength, my life, +
Of course, because I’ve lost my wife. +
