---
title: "Trust"
url: "/trust"
aliases: []
description: "On trust"
date: 2018-10-01
lastmod: 2018-10-02
draft: false
acknowledgement:
categories: ["Poems"]
tags: ["poem", "poetry"]
people: []
places: []
locations: ["San Francisco"]
---

= Trust
Anton Podviaznikov <anton@podviaznikov.com>

Why don’t you trust me? +
Why your default assumption is a betrayal? +
If someone betrayed you doesn’t mean you should stop trusting the world or people. +
Distrust blocks power and possibility connection and closeness. +
It’s a border that should be crossed. +
It builds the wall which should be broken later. +
It all requires energy that we could spend elsewhere. +
Why do we start from there? +

Why can’t you pick another default? +

When I see that you don’t trust me I start questioning my trust in you. +
I become suspicious. +
I start questioning your decision making and your values. +
If betraying someone is so easy in your mind, I really start to worry that you can do it. +

And it drives us further away. +

Stop doing it. +
Why are you so angry? +
I thought that pain will make you kind and expose to love. +
Why do you bite? +
What did I do to you? +

I don’t want to play this catchup game gain. +
I don’t want to prove my intentions. +
It’s is boring. And words don’t mean a lot in those conversations. +
Actions are much more important. +

Please change your defaults. I beg you. +

All this anger. I’m getting scared. +
I know the reasons for it, of course. +
I know those are just emotions. +
And that they are temporary. +
But they still have an impact on me. +
I heard you wanted me to suffer +
just because you felt in danger. +

This worries me. You instinct reaction was to hurt me, +
But the source of your pain had nothing to do with me. +
It was all inside you and your past. +

I’m afraid. I can see this fire off in the future when I’m not ready. +
I see how you could act immediately under the emotions. +
How you would hit me in my weakest spot. +

This escalates quickly. +
Trust breeds trust. +
Distrust breeds distrust. +
It’s hard to build anything valuable on such foundation. +
I’ve been there. +
I don’t want to be afraid to speak my mind. +
I don’t want to censor myself to prevent your emotions and + 
Actions that follow from that. +

I want safety. I want to know that it is safe for me to speak. +
That my words will not cause you to act and make me suffer. + 

I want to talk to you the same way I talk to myself. +
That is my ultimate goal. That is what I’m looking for. +
This is ultimate intimacy. +
