---
title: "Truth"
url: "/truth"
aliases: []
description: "Catching Truth"
date: 2018-04-30
lastmod: 2018-10-30
draft: false
acknowledgement: 
categories: ["Poems"]
tags: ["truth", "poetry"]
people: []
places: []
locations: ["Berlin"]
---

= Truth
Anton Podviaznikov <anton@podviaznikov.com>

Foolish me. +
I thought I knew a thing. +
Of course that arrogance comes with age and ego. +

Foolish me. +
I thought I knew what life is. +
Of course, I didn't. +
How could I? +
Living in a head +
Would not provide an answer. +
The same is right for living in a world. +
The Truth is always in the balance. +

It's not here, and it's not there. +
It hides every time you try to grasp it.  +
It's like a quark, +
It's opposite of what you just learned. +
It jumps around the corner, +
It hides from you, +
And you always try to seek it. +
It's a phantom, +
It's a ghost that can't bee seen. +
The moment you grab it evaporates. +
And you need to start from scratch. +

The Truth can't be described, +
It can't be said in words. +
It's bigger than that. +
It's like a God, or better like water + 
That you want to take with your bare hands. +
You feel it, you are on the grasp of it, +
And then it's gone. +
It might become ice or become a cloud. +
It will be the source of life for flower or a tree, +
for fox or for a bee. +

But you would never be able to grasp the whole complexity of this. +
How can water do this? +
It will always be a speechless miracle. +
Water can be calm or powerful, +
The same is true for the Truth. +
It holds every thing. +
It holds polarities. +
It contains Universe. +
Sadness and happiness. +
Joy and sorrow. +
The Truth even contains falseness and lie. +

Catching the Truth is like catching a bird by the tail. +