---
title: "Where are you?"
url: "/where_are_you"
aliases: []
description: "How to find strength"
date: 2018-05-01
lastmod: 2018-05-01
draft: false
acknowledgement:
categories: ["Poems"]
tags: ["poem", "poetry"]
people: []
places: []
locations: ["Berlin-San Francisco"]
---

= Where are you?
Anton Podviaznikov <anton@podviaznikov.com>

Where are you Neil? +
Where are you Vaclav? +
If you couldn't enlighten everyone then +
Who would do it now? +

Who is even concerned nowadays with humanity? +
Professors, presidents, directors. +
They have no vision and no wisdom. +
They do not seek knowledge +
And do not love people. +
They do not enjoy life +
And don't believe everyone should either. +

Who would guide us? +
We have your books and we have memories. +
But we are weak and often distracted. +
What is the source for our strength? +
How do we start reading again? +
Instead of repressing our anxieties and fears +
with alcohol and media? +

How did you find the strength? +
What brought your love? +
How do we find unity? +
How do we find motivation? +

We are good only for consumption these days. +
It sucks everything out of us. +
It dumbs us and we are too weak and lazy to resist. +

Please, send us your strength. +
How did you go against ignorance and systems? +
Where did you get that energy? +
Who feeded your dreams? +
We don't have any of them anymore. +
Weak, dreamless, anxious, isolated creatures. +
We only have vague memories of the great heroes. +

We are in pain. +
Maybe this will unite us? +
Maybe our pain will create collective love? +
And love would give us energy. +
And with energy we will seek wisdom. +
