---
title: "Women"
url: "/women"
aliases: []
description: "About women"
date: 2018-09-10
lastmod: 2018-09-29
draft: false
acknowledgement:
categories: ["Poems"]
tags: ["poem", "poetry"]
people: []
places: []
locations: ["San Francisco"]
---

= Women
Anton Podviaznikov <anton@podviaznikov.com>

Woman, +
Why did you do that? +
I've been by your side all my life. +

I saw your tears. +
I wanted to protect you from men. +

How stupid was I. +
I despised men and adored you. +

First as a mother. +
As a friend, +
As a partner, +
As a lover. +

But every time you betrayed me, woman. +
You didn't need my protection. +
You didn't care about me or value me. +
You betrayed me and hurt me every single time. +
And when you came back it was all too late. +
Part of me was dead. +

As a mother you abandoned me. + 
I needed your protection in those rare moments. +
But you didn't care. +
As a friend and lover you always went somewhere else. +
You thought that I'm unbreakable and that you'll always be able to return. +

Woman, why can't you see? +
I have feelings. As any other man. +
It's you who made me tough and emotionally inaccessible. +
I became tough not because of men, but because of you. +
You forced me to close my heart more and more with each year. +
You blamed masculine nature for inaccessibility. But wasn't you the one with whom I grew up? +
The one I went to school with and spend my adolescence and first adult years. +

You were the mother. +
You were the friend. +
Your were the partner. +
You were the lover. +

There are no one to blame for that. +
Not a mystical nature of men. +
We didn't grow up on trees. +
We were abandoned and forced to close our hearts. +
You numbed us. +

And only deep understanding of life itself can help to revitalize me. +

Woman, I know what life is. I'll revive my heart and show you real love. +
Love that comes from knowing what is the pain. The love that is non-judgmental and unconditional. +
Woman, you'll see. Past is the fuel for the love. The one who was really hurt can't hurt no one. +

Woman, you are like Mother Nature. +
Loving and deep and encompassing. +
But you are destructive force too. +
You are a hurricane, you are plague, you are tsunami. +
You give life but you can take it too. +

This is my pledge. I finally see the duality of life. I see the need for both sexes. +
I see the duality of each sex. I see all of that inside myself. +