---
title: "5 years"
url: "/5_years"
aliases: []
description: "5 years. Self-reflections and planning the future"
date: 2015-08-27
draft: true
acknowledgement: 
categories: ["Writings"]
tags: ["life", "travelling"]
people: ["Alain de Bottom"]
places: []
locations: ["Istanbul"]
---

= 5 years
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-04
:docdate: 2018-01-04
:nofooter:
:document_type: writing
:tags: "life, travelling"

I often thought what would happen in my life in the next 5 years. 
Previously I wanted to have a possibility to predict my future and plan for it accordingly. 
But at some point, I realized that it’s almost impossible. 
At the beginning of August 2010, I left Ukraine. 
There is no way I could predict 5 years ago what would happen next.

I left Ukraine for Montenegro. 
I lived and worked in this small and beautiful Balkan country for almost 1.5 years. 
I fell in love with the whole region, I changed my lifestyle and attitude to a lot of things.
I learned to enjoy life and invest time in myself. 
Then followed a short period in Bay Area and I became digital nomad afterward. 
I lived and worked "on the road" from June 2012 until May 2014. 
During this period I visited Serbia, Croatia, Bosnia, Montenegro, Ukraine, Germany, Brazil, Mexico, Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Ecuador, Argentina, USA, Turkey, and Macedonia. 
Travel did become part of my identity, and it hugely influenced my outlook, 
but before 2010 I've been outside of Ukraine only once and travel around the world wasn't even a realistic option in my mind.


Professionally I switched job at the big outsourcing company in Ukraine to the small product/service company oriented on local Montenegrin market. 
Then I briefly tried freelancing and finally joined CircuitHub as founding team member. 
At CircuitHub we attempted to build a great product and a great company (the one we all enjoyed working in). 
I still hold to a lot of values/ideas I learned during 1.5 years with the company. 
We went through YCombinator Winter 2012 batch, we tried to build a distributed company, we used Node.js in 2011 (very early days for this technology).

After CircuitHub, I had my second stint at freelancing, attended HackerSchool/RecurseCenter, 
did freelancing again and finally moved to San Francisco to work for early-stage startups (human api and runnable).

In 5 years I tried almost everything: outsourcing, freelancing, early-stage startups, starting my own company. 
I wrote software for different industries: from the government sector to health care, from the tool for electrical engineers to the social site with funny pictures.

My home country in the last 5 years went through electing Victor Yanukovych as president, 
making the revolution against his regime, Crimea occupation and war against Russian Federation. 
I don't know anyone who predicted those events 5 years ago.

In 2010 while being a programmer in Ukraine I'm pretty sure I didn't know what YCombinator was, HackerSchool/RecurseCenter didn't exist yet, 
"digital nomadism" was probably just starting to become a thing and so on. 
The point is a lot of things are not possible to plan because they might not exist yet or you might be unaware of them when you start planning. 
Alain de Botton in the https://www.youtube.com/watch?v=bTDGdKaMDhQ[video about Meritocracy] points to the fact that a lot of things in life happen randomly. 
After analyzing last 5 years, I have a very similar feeling about lots of events. 
I feel that I have some control over events during next year, but that is not true for the 5 years period. 
Life by nature is dynamic and unpredictable. It's easier just let it flow and enjoy the process.

So what is coming in the next 5 years? Honestly, I don’t know. 
But I’m excited about all new challenges and experiences. 
My "circle" is getting bigger and there are much more things to learn than before.
