---
title: "Eastern European Man"
url: "/eastern_european_man"
aliases: []
description: "The Man from the Eastern Europe"
date: 0-00-00
draft: true
acknowledgement: 
categories: ["Writings"]
tags: []
people: []
places: []
locations: []
---

= Eastern European Man
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-03
:docdate: 2018-01-03
:nofooter:
:document_type: writing
:tags: ""

Warning, unfair generalization and reversed sexism ahead.
This is just an exercise to describe one of the archetypes, don’t take it too seriously.

Eastern European Man appears to be smart, tough, direct and confident.
He appears to be able to loudly disagree with a group of people. 
He is ready to put himself into the opposition/confrontation to the group of people of any size.
He appears to be also quite in most of the life situations. He looks like as if he knows something about life. 
He looks calm and it might seem like his calmness comes from inner security and integrity. 
Maybe he looks like he is at peace with himself and life.

However, underneath it is not like that at all. Eastern European man is a child in a body of an adult.

His quietness and calmness come from the fact that he was never taught to express his emotions properly 
and integrate them into his life.

His directness in expressing unpopular opinion comes not from the fact that he is smart 
but from the fact that no one taught him how to behave in groups people of people. 
When Eastern European Man meets Westerner (and especially American), he sees a shady person who never speaks his mind. 
Immediately he feels superior. 
But he doesn’t know that it is him who is shady in reality. 
You can't do much with direct, but aggressive and careless person. 
You can't build team or company, you can’t build friendship or relationship. 
Aggressive directness is toxic and counterproductive.

No one taught him that the best strategy for life is to be kind to other people, and no one taught him that there are different ways of expressing one opinion. He only knows the way in which you isolate yourself, make other people feel bad (or stupid) and close possibility for the future dialog and development of relationships.

Have you been to programming conference or event? 
There is always this Eastern European Man in the audience who would ask some strange question 
to not help improve conversation or common understanding of a problem but to show off. 
Eastern European Man tries to show his intellectual superiority to everyone: 
his partner, colleagues, everyone else. 
It is acceptable to him that he would hurt every one of them in the process. 
But at least he is a "true man", he sticks to his principles and stays direct and "tough" at all time.

Eastern European Man always competes. He is never _for_ something, he is always _against_. 
He competes against everyone else. No one taught him that competition is good, but it should be in the balance with cooperation. 
The combination of cooperation and competition is the secret to every game, and to life and evolution itself.

Eastern European Man shouts at his colleagues and insults them. 
Just to show who is the boss, who is the smart one and the tough one. 
The tougher you are, the better you are. 
He would show that he does not care about you and despises you. 
Because he is independent and a loner. But, of course, it comes from the inner insecurity.

Eastern European Man swears a lot. To him, profanity is the symbol of adultness because only adults can do this.
But in fact it is opposite, real adults _know_ swear words and have the discipline and wisdom to not use it in every sentence.

Eastern European Man jokes at the expense of other people. 
He would mock and make fun of his friends. 
It will always be one-sided. Nothing like that should happen to him. 
For the Man, a joke is a tool to boost ego and to establish his superiority towards the other people.

In fact, Eastern European Man preoccupied with his ego all the time. 
Building it up makes him feel better. No one taught him that is is better to go the opposite direction with ego.

Eastern European Man doesn’t know the difference between information, knowledge, and wisdom. 
He would think that he is smart just by knowing a lot of different facts (which is information). 
He doesn’t know that there is something beyond that.

Eastern European Man looks grumpy. And you would think it’s because he is so smart and read great literature 
and philosophy and he is preoccupied with understanding the world and life. 
But it’s because no one told him that he can be happy and how do achieve that. He only knows how to be bitter about life.

Eastern European Man is of course nihilist. He believes in "Nothing Mattersness." 
Everything is someone else's fault, nothing can be done about it. 
Only he is enlightened but no one from these stupid people smart enough to realize his greatness and start listening to him.

Eastern European Man is of course selfish. 
He doesn’t believe in people, collaboration, and action. He is not preoccupied with self-transcendence.

Eastern European Man is, of course, unhappy person. But more than that he would be very willing to ruin fun for everyone else. If a group of people is having fun and the man can’t participate, he would ruin the mood for everyone (by shouting or saying stupid things). If he can’t have fun, no one should, and it’s his right to make everyone feel in tune with him.

Eastern European Man wouldn’t dance. He would explain it as a trait of a "real man," however, 
it seems like he couldn’t integrate his body together with mind.

Eastern European Man has no feelings. He is a person of the intellect, and he is above emotions of course. 
But of course, is is because no one taught him how to integrate his emotions and feeling with his mind and body. 
Eastern European Man doesn’t know that they are essential, he denies them, and is scared of them.

Eastern European Man is very romantic and believes in magic. 
For some reason, he thinks that other people can read his mind and read his feelings without him saying a word 
or expressing any emotions.

