---
title: "Implementation details"
url: "/implementation_details"
aliases: ["/implementation-details-46jk9l8xx15"]
description: "Working on the wrong level of abstraction"
date: 2016-11-12
draft: true
acknowledgement: 
tags: ["post-modern world", "future", "politics"]
people: []
places: []
locations: ["San Francisco"]
---

= Implementation details
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-28
:docdate: 2017-12-28
:nofooter:
:document_type: writing
:tags: "post-modern world, future, politics"

We live in a post-modern world driven by the discussion of the wrong issues. It's an obvious thing to say when the year 2016 comes to an end.

"Discourse" is mainly centered these days around things we shouldn't even care about: tax breaks, income tax rates, problems of global terrorism, immigration etc.

In my opinion, there is no need for us now to agree on specific policies and actions - those are implementation details. We don't even need to agree on some ideas either (e.x. idea of the free market etc). Ideas are very vague, we all understand them differently, they can be easily misinterpreted. But the main problem with ideas is that they bundle too many things together (e.x. we bundle both dreams and ways of implementing them - the idea of capitalism or democracy for some reason nowadays carry the assumption how such idea should be implemented).

What I think we should discuss more are values. Values usually remain unstated both in interpersonal dialogs and discussions on the higher levels. I think we should strive to change this situation and be very explicit in stating our values and enquiring about values of people and systems we deal with. Before we even start discussing why some idea or policy (implementation detail) is good or bad we should clarify each others' values and rank them. We should try to find some consensus after such discussion.

The next step would be to reflect what are some problems with our existing values and dream up of some possible future values we would like to have. I think that political parties, social movements, people organizations should work on this level. They used to work on ideas and ideologies in the XX century, and on specific practical policies in the past few decades.

We should approach thinking about future in the following way:

1) let's identify our current values and their precedence

2) let's find some problems with our current values

3) let's dream up of what values we would like to have in society in 10, 20, 50, 100 years (and not what the income tax should be in 2018)

4) let's compile those values in a well-defined system and focus on talking about it

The rest is implementation details. Yes, it can be very difficult to come up with the ideal solution in this extremely complex and interconnected world, but some progress and solutions with positive impact are always possible.

For my engineering friends, I have a following metaphor for the issue I'm discussing.

We have a very complicated system because we coupled interfaces and implementation details. Everything is so messy right now that it's hard to see what is where. In my opinion values are interfaces. They are high-level things that should be clearly defined and exposed. Interfaces are important because they allow communication between actors. Policies, actions, decisions, processes are implementation details. They should be implemented in the best rational way (given all the constraints) to comply with defined interfaces. E.x. the income tax is not a question of big importance in such approach. You simply pick the one that helps system to conform to the defined interface (achieve desired declared values).

Another great benefit of such clear separation is that it's easier to run the migration on a live system, that is, provide a real positive change. It's much easier to understand interfaces between system A and B and came up with appropriate plan than to understand messy coupled beasts we have now.

Our branches of life: economy, technology, philosophy, education, science etc should be values-driven. They should act in order to achieve future societal values and not some very specific metrics they rely on now.

To reiterate, I think that _implementation detail_ < _idea_ < _values_ < _desired values_. Let's steer discussions and the whole discourse to the appropriate level of abstraction.

Also working on the proper level of abstraction can eliminate whole classes of problems automatically. E.x. if only we can rethink our values, a lot of issues we are discussing today would be eliminated: terrorism, an immigration crisis, tax issues and global warning. This sounds too idealistic and naive in the 2016 but I think humanity did it before and can switch to the new way of thinking again.

I don't want to discuss now what one should do next after agreeing on values, that is, I don't want to discuss implementation details. I think 1) it's an easy problem to solve once you have a clear system design , 2) it would contradict the whole message of this essay, which is _start from the most important issue first_.


