---
title: "Joke on Us"
url: "/joke_on_us"
aliases: []
description: 
date: 2018-01-21
draft: true
acknowledgement: 
categories: ["Writings"]
tags: ["comedy", "politics", "discourse", "daily shows", "modernity"]
people: ["Stephen Colbert", "John Oliver", "Jon Steward", "Donald Trump", "George W. Bush"]
places: []
locations: ["San Francisco"]
---

= Joke on Us
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-22
:docdate: 2018-01-22
:nofooter:
:document_type: writing
:tags: "comedy, politics, discourse, daily shows, modernity"

Imagine two people. They are friends or colleagues or neighbors.
One person starts telling jokes about another one. All the time. 
He says how stupid that person, how unreasonable all her thoughts are, 
how limited and second-class she is.

What would be the outcome of such behavior? At least it will be alienation, at most, it would be 
rivalry and fight.

One person pumps his ego up at the expense of another person while destroying the possibility of the 
dialog, cooperation and any constructive type of relationship.
The second person might just either withdraw forever from such type of abusive relationship or will 
mirror the attitude towards her and start the fight.

And now think about "progressive" liberal media in the US. 
Starting from 1999 till today people like Jon Steward, Stephen Colbert, John Oliver
run highly popular daily/weekly shows where they laughed at people with whom they disagree.
The result of that is highly divided society each with each own media.

I’ve heard that such daily shows are a unique feature of American culture where it’s allowed to make fun of anyone. 
I’ve been told that that is precisely the symbol of democracy. 
That might be a good point if such shows were merely additions to some serious media programs.
But as far as I can tell, at least for the young people, those programs are _the main_ source of political discourse.

Those programs divided people on "right"(pumping the egos up, because who don’t want to be "right" 
and it feels great to be on the "winning side") and "wrong".
It is unfortunate, because I saw this happened in Ukraine in the years between 1991 and 2014.
Once you have divided society it’s tough to bring it back.
Usually, some tragic events follow such situation.

On top of dividing society, those programs, and those comedians completely _trivialized_ discourse. 
Everything became a joke. There are different metaphors for life. 
I think John Oliver's metaphor is "life is a comedy… dark comedy".
When you make fun of Dalai Lama, Snowden, religions, elections - you create a world where there is no serious subject anymore. 
Every topic is a comedy, which is there only for our entertainment. 
In fact, the current President of the US is an entertainer and for a lot of people idea of him becoming a President was a joke.
But it’s the logical consequence of the world created by daily shows and comedians who turned to be political commentators.
In the world of "old" political discourse, Donald Trump would never become a President. 
But in the "new" world of comedy, it’s precisely him, who should be a President.

On top of that, comedians bring a lot of pure anger into the world. 
Please watch "Stephen Colbert at the 2006 White House Correspondents' Dinner" video and his commentary on it. 
He went there to make fun of President Bush, and he made him extremely angry by the end of the evening.
In what moral framework it is acceptable to consciously make other people angry? 
He had no intentions for President to change his positions, opinions or actions.
Because if he did, he would approach the problem differently. 
All he cared about his fame. 
He prioritized his ego and made President of United States angry.
When someone is angry, it’s quite difficult to act and reason appropriately. 
You become less rational, more aggressive and bitter.
It doesn’t matter if I agree with policies of President Bush, I think Stephen Colbert is a "bad guy" here. 
He is essentially a high-school bully.
Instead of being engaged in a constructive dialog he went for inappropriate behavior of the poorly developed teenager.

If you are liberal, why do you waste your energies blaming Trump, conservatives, Fox News, etc? What is the point in such blame?
At least half of the responsibility lies on liberals. 
They helped to create the world we see now. 
And the only constructive way is to withdraw blame and hatred,
analyze own mistakes and follow up with some conclusions and lessons learned about own behavior.

Change yourself first.
