---
title: "Managers and Ministers"
url: "/managers_and_ministers"
aliases: ["/managers_and_pms"]
description: "Ministers are managers"
date: 2018-01-08
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["Ukraine", "politics", "ideas"]
people: []
places: ["Ukraine"]
locations: ["San Francisco"]
---

= Managers and Ministers
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-17
:docdate: 2018-01-17
:nofooter:
:document_type: writing
:tags: "Ukraine, politics, ideas"

In 2013 - before the revolution in Ukraine - I had this idea, that Prime Ministers and CEOs of large multinational corporation share mostly the same skills.

In 2013 it seemed to me that my home country had two principal problems: corruption and lack of talent. 
My idea was supposed to solve both of them.

Since Ukrainian politicians and government officials were poorly educated, corrupted and incapable of reforming the country in over 20 years, 
I thought that we need to invite professional managers from respected and successful foreign companies. 
Of course, to such professionals notions of corruption would be unthinkable. 
I was thinking about making offers for CEOs of Nokia, IKEA, Ericson, and the likes. 
It would work like that: pay competitive global salary, with 4 years contract and bonuses tied to the agreed KPIs.

I remember pitching this idea to few Ukrainian friends and, of course, they said that I was crazy.

There were two main arguments against it.
A foreigner can't run a country because she is not a patriot and her interests may collide.
My counterarguments are:

 - Ukrainians stole much more money and made much more harm to Ukrainian state than any foreigner ever did. 
It is as simple as that. 
Most of the Ukrainian politicians and managers live at the bottom of the Maslow pyramid of needs - they don't invest in educating themselves, 
and they don't care about building a proper state, that is why they are least qualified to run the country.
 - PM has nothing to do with international politics and national security. It's purely managerial role, and foreign policy and army are controlled by the President.

The second usual argument was that we can't afford to pay high salaries to PM and Ministers.
If you mention salary of 100K USD per year in Ukraine for the Prime Minister some people might go crazy. 
However, I think that is because they lack perspective. We live in the globalized world and in to compete for the top talent you need to pay premium salaries. 
Prime Minister of the country can't earn less than creative professional in the Silicon Valley. 
In fact, I think Ukrainian PM should earn around 1M USD per year.

According to https://en.wikipedia.org/wiki/List_of_salaries_of_heads_of_state_and_government[Wikipedia article] salaries of state leaders are following:

 - Ukrainian President - 94K USD
 - Russian President - 136K USD
 - France PM - 200K USD
 - Sweden PM - 220K USD
 - Germany PM - 300K USD
 - New Zealand - 325K USD
 - Luxembourg - 340K USD 
 - Switzerland PM - 495K USD
 - Australia PM - 507K PM
 - Singapore PM - 1631K USD

So why, I'm proposing to pay second biggest salary in the world to Ukrainian PM? 
I think, except Singaporean PM, those wages are unbalanced. 
Those are government salaries. Please, go look up salaries for CEOs of big companies. 
Most top companies pay well above 1M USD per year in base salary plus huge bonuses. 
Government salaries are lagging here, but that means they attract talent of lesser quality. 
If you want best managers, who have an excellent education and excellent track record - pay appropriately.

If you still think 1M USD per year for PM is too much, please check out salaries for football coaches of national teams. 
In 2016 even Ukrainian National manager earned 170K Euro (which is higher than the wage of Ukrainian President). 
Top 9 European coaches earned between 1M Euro and 5M Euro per year. Fabio Capello, while coaching Russian National Team earned ~11M USD per year. 
Think about those numbers, and compare them to the salary of the President. Why did Capello receive salary well above the average? 
Because he is top manager coming into the average team and trying to make the difference.
Football coaches manager just 20-30 people, yet they receive salaries that are 20-100 times higher than for the people who manage the whole state. 
I'm not arguing that they salaries should be reduced, I'm arguing that even higher salaries should be paid for PMs of the countries which are serious about making the leap.

If you think about those numbers with a clear head, you will realize that proper professional government can deliver value much higher than the salaries they receive.

I want to acknowledge, that since the revolution Ukraine took a bit similar path to the one I described. 
In fact, decent amount of Ministers were foreign citizens. However, I think it's not enough. 
I think PM should be a successful international top manager. The same goes for Ministers. 
I think they should come from highly developed countries of Western Europe, Asia, etc. 
They should have the very best education in the world top schools.

And you know what? I bet some of these successful managers would love to come to Ukraine. 
Because it will be a challenge for them - to modernize a country with 40M people. 
We talked about salaries a lot, but the challenge and the prospect of the big impact are what really drives these people. 
Salary is just a way of showing that you are serious about the project and believe in fairness.






