---
title: "Non-believers"
url: "/non_believers"
aliases: ["/nonbelievers-gg1xm7woojo"]
description: "Refusal to believe in the systems' stability in the modern world"
date: 2016-11-24
draft: true
acknowledgement: 
tags: []
people: ["Zygmunt Bauman"]
places: []
locations: ["San Francisco"]
---

= Non-believers
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-28
:docdate: 2017-12-28
:nofooter:
:document_type: writing
:tags: ""

Recently at work, we were discussing 401K, which can be defined as personal pension fund that you can contribute to during life and use after the age of 65. I wanted to be persuaded to use it and listened to all the arguments made by my colleagues but they didn't work for me.

I tried to think why having 401K is a no-brainer for my American friends and why my personal perspective was so different.

The answer lies in my personal background and in my comprehension of history, states, society, institutions etc. It seems to me that my colleagues believe in the stability and immutability of the existing system they live in. Consciously or not they bet that in 40-60 years the system they live now would be basically unchanged: the United States would still exist as a country; banks and financial institutions would not go bankrupt; laws to protect savings of the regular people still would be in place; balance of social power would remain similar to the one we have today and middle class would still exist in similar proportion and have some political voice. This is pretty tough bet to make in my opinion, the probability of change in each system might not be high, but overall probability of general change is much higher - because it's multiplication of individual probabilities.

To be fair, I'm very happy that my colleagues can hold such belief in the system's stability and predictable future. To some extent, I would like all of us to have this belief because it is much easier to live when uncertainties are low.

However, my personal background does not allow me to believe in such story even if I wanted too.

I think this belief in the unpredictability of the future is quite common for the Eastern Europeans. And there are historical reasons for that.

Here are the facts.

I'm older than Ukrainian state.

My grandparents and parents grew up in the country that disappeared in 1991. All of them lost their savings. All of them experienced a radical change of the way of life, values, ideology etc. They would never be able to anticipate coming changes few years in advance.

My grandparents lived through WWII as kids.

My great-grandparents were born in the Russian empire, lived through WWI as children, witnessed the collapse of the empire, revolution, civil war and emergence of the new state of Soviet Union.

Even in my not long adult life I already experienced 2 revolutions in Ukraine and 1 war. I lived through the countless revolutions and wars across the globe, global economic crisis, banks going bankrupt and people losing their savings.

If I was born 100 years earlier - in 1887 instead of 1987 - I would experience following events:

by the age of 27, I would see WWI starting
by the age of 30, I would see Russian revolution, the collapse of Russian empire and emergence of the new states
in my late 30s and 40s, I would live through Stalin's repressions and genocide
by the age of 52, I would see the start of WWII that would last 6 years
by the age of 60, I would witness the start of the Cold War (and would probably die before it ends)
if I could live till the age of 104 years I would see the collapse of the Soviet Union
I think that it's valuable to map correctly scale of one's life to the history. The speed of history is increasing with each new generation. Many changes may and will happen during the course of 80 years of person's life.

Exact changes are unpredictable and uncontrollable, but with high confidence, we can predict that extreme changes will happen in the next 40-60 years, and we should plan for this fact.

Another Eastern European - Zygmunt Bauman - describes our times as "liquid modernity". Those are the times of chaotic change. We change ourselves constantly, we flow through the life changing places, jobs, life partners and even values. If we are changing ourselves, how could we expect bigger systems - states, banks, culture, etc - to remain stable and even exist in half a century?


