---
title: "On abundance and moderation"
url: "/on_abundance_and_moderation"
aliases: ["/on-abundance-and-moderation-9793lx1rrkx"]
description: "World of everything and nothing"
date: 2016-10-10
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["abundance", "moderation", "consumption", "consumerism"]
people: ["Goethe", "Neil Postman"]
places: []
locations: ["Hong Kong"]
---

= On abundance and moderation
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-08
:docdate: 2018-01-08
:nofooter:
:document_type: writing
:tags: "abundance, moderation, consumption, consumerism"

Goethe wrote, "One should, each day, try to hear a little song, read a good poem, see a fine picture, and, if possible, speak a few reasonable words". 
We can take few good points from this wisdom but let focus on one for now. 
What is interesting here to me is that Goethe didn't advice us on reading several poems per day, he didn't advise us on listening to the whole music album or talking a lot.

Almost every major world religion I know has the concept of self-restraint. 
That is restricting ourselves during some periods for food consumption, sex, sleep and other sources of physical pleasure.

There are also a lot of proverbs on this topic in each culture. In my country, we have a saying that "what is a lot is not good." 
Neil Postman also said "if we eat too much food ... we turn a means of survival into its opposite." This wisdom existed for thousand of years. 
Are we forgetting it now? If we are, why is that?

Why do we need to restrict ourselves? Why can't we have it all and at once?

Maybe because we should be able to control our wishes and our vices, otherwise they will become our masters and drive our decisions, actions, thoughts and destiny at the end?

Or maybe moderation allows us to enjoy something better? If we have unlimited access to some resource can we truly be able to fully appreciate it? 
Isn't abundance of something destroys its value? This sounds very similar to law of open markets. 
Can we still truly enjoy our ice-cream if we eat it every day? 
Or can we truly appreciate some sport game if we can see it every day instead of once per week as it was only few decades ago? 
Those examples are countless.

Or maybe moderation provides us with variety? If we can't spent all our time on one thing we will try something else. 
And maybe this variety is a key to our development and health.

Or maybe abstaining from something makes us better? It allows us to better understand our true nature and true desires? 
Maybe it makes us more resilient to difficulties?

Or maybe restriction of some sort allows us to focus and turn on from one category of needs (e.x. physical) to another (e.x. intellectual, spiritual etc)?

Or maybe idea of artificial restraint presents us with the change in our routine which is important on recognizing when we do something on the autopilot? 
Maybe it helps us to to fight boredom? 
It allows us to revisit our habits and default behaviors? 
E.x. instead of falling back to eating something when we are bored we can try to discover new source of joy or even find some new meaning in our actions?

Or maybe it will allow us to be more careful with our choices. If you can listen to only one song today, which one it will be? 
You'll probably try hard to make it count and make maximum of it.

Or maybe restriction allows us to have more unclaimed free time that we can spend on our own, reflecting on who we really are and what is really important to us?

No matter what was Goethe primary reason for writing the phrase mentioned above I think we should try to take his advice to heart. 
Let us see if we can limit ourselves in our world driven by consumption. 
Are we even able anymore to listen to one song per day, do one physical exercise, read one story/essay, eat one nutritional (and tasty) meal?

How would such change reshape our personalities and tastes? 
What skills would we acquire? 
Would we be less anxious or more? What would we do with our newly acquired free time? 
How would we spend it? Learn a new language, meet our friends, walk more and think more, do some community work, learn to play some instrument, invent a new game? 
I don't know, but it definitely puts you in control, it makes you to design your life and. Are we up to the challenge, are we capable of doing this?

It's pretty clear nowadays that abundance of food leads to obesity, diabetes and other health issues. 
Those changes are physical and easy to see. But what about abundance of media, technology, entertainment? 
What impact huge quantities of those things have on us: on our bodies, minds, souls, consciousness, attention etc? 
Are we even aware of changes in those areas?
