---
title: "On reading"
url: "/on_reading"
aliases: ["/on-reading-q85yqjgrrrm"]
description: "My relationships with reading"
date: 2016-10-12
draft: false
acknowledgement: 
tags: ["books", "reading"]
people: []
places: []
locations: ["San Francisco"]
---

= On reading
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-28
:docdate: 2017-12-28
:nofooter:
:document_type: writing
:tags: "books, reading"

In this post I’ll present my own relationships with reading, how it evolved over years, current challenges I’m facing with it and will think about possible solutions. Here we go.

## Reading: first years

Before school (up to 7 years) I was a very slow reader, I struggled a lot and my mom struggled to teach me. This problem continued well into the first half of the first year of school. My reading speed was one of the worst in the class. I vaguely remember what happened but I think during the winter break I picked up a popular Soviet children adventure book The Adventures of Dunno. I liked it a lot. I read it very slowly but after finishing I was hooked (and my reading speed improved dramatically) and continued with two other books from the series. Dunno/Neznaika, in my opinion, was like Harry Potter for Soviet and some post-Soviet kids like myself. I might have read at that time few more books in the same genre, like Gianni Rodari’s Chipolino and some others. The point is that by the end of my first school year I enjoyed reading a lot and my reading speed was one of the best in my class.

I think it is important to give a context to these first years. I grew up in a small western town in post-Soviet Ukraine. What was good about that world is that we didn’t have much of now traditional media entertainment. We had only few TV channels (3 to 4 depending on a weather), they didn’t work during the day (so when I was back from school, there were not only no cartoons to watch but also no TV). Every weekday evening we didn’t have electricity for 2 hours. So basically your TV entertainment was reduced to a tiny fraction of the time: we might watch either news or one TV show or one movie. We didn’t have many cartoons either, it was usually 5–10 minutes cartoon during the evening program for the kids and 1 hour of some Disney cartoons on Saturday mornings. That was it.

Now imagine Ukrainian winter in the 90s. You can’t go much outside (because of the weather) and the days are extremely short (it's getting dark around 4PM). So you are spending a lot of time inventing your own entertainment. Reading was usually the top choice. I also had few old video games on the Nintendo-like console. But to be honest I don’t have memories playing video games every day and for long periods of time.

I would spend summers in a village with my grandparents. My usual schedule was following: help grandma to look after chickens before the lunch (it is very boring activity so a book is a savior in that situation) and then play soccer in the evening when it’s not that hot anymore. That is it. The rest of the time you have nothing to do. Once again you need to find your own entertainment, for me, it was cycling and reading. Reading was my favorite activity.

So during elementary school years, evenings without electricity, winters with short days and summers I read a lot. If was mostly adventure books. I didn’t have any reading plan yet. I would pick up some books from local library. During this time I read about adventures of Hercules, The Wonderfull Wizard of Oz, The Wonderful Adventures of Nils, Mark Twain's Adventures of Tom Sawyer and Huckleberry Finn, Timur and His Squad, I’ve read also some fantasy back then (don’t remember titles anymore) and I’ve read more children adventurous literature of the Soviet era.

Those were my first years reading. I think this stage was mostly about adventures (I read some others more serious books at the time, but I think they were rarer at this period). For me, it lasted from 1993 till 1997-98. I would call it “Harry Potter” stage. However, I have never read or watched Harry Potter because the first book was published in 1997 and it came few years later to Ukraine. By that time I was mostly done with this genre.

## Middle school

During this stage, I read most of the things we were reading for the school program but sometimes on my own schedule. A lot of works I read before the program because again I had a lot of free time on my hands and some I discovered outside of school (e.x. at my parent's or grandparents' library). In this period I read mostly classics of French, Ukrainian, and Russian literature (XVIII and XIX centuries), I read also some science fiction for the first time and I read a decent amount of books about WWII, about partisans, about resistance. I read also other historian adventures about cossack, pirates etc. Occasionally I would pick up some random books like Viktor Suvorov's explanations of Soviet and world history of the XX century.

The main theme during this stage was history (which I enjoyed a lot) and some adventures but by real people.

## First transition

During my high school years I moved to the big city, it was the beginning of 00’s years, the country was very different. We had a lot of TV channels, radio stations, cinemas. There were a lot of things one could do after school. The environment changed dramatically. I also lost some personal interest in books. I still read most of the works for the school program, but it was rare that I would find a book that I would read with the joy for few hours per day. Basically, my taste and interests changed but I wasn’t able to find a replacement yet. School program was of no help. We read usually something I wasn’t interested that much at the moment. Topics were unappealing to me.

I don’t remember exactly when and what happened but I think at the end of my high school during my university years I discovered works of Ernest Hemingway and Erich Maria Remarque. I read at least 5 of books from each of them in those few years. It was the literature of XX’s century, it was more familiar, easier to grasp and relate too. I think in retrospective it was also interesting to me because those books were about Lost Generation of Western Europeans who lived through and after the big shock of WWI. And it seems to me know that theme is very appropriate to Ukraine I know.

The collapse of Soviet Union probably had a similar effect on its' former citizens like that to Europeans who witnessed WWI. Country collapsed. People didn’t know what to do in life anymore, they didn’t know what the world and life are becoming, some of their became were obsolete, other values were constantly attacked by the new order. I lived in Ukraine among the lost generation. Imagine growing up in one world for 30 years and then that world would disappear in one day. Not everyone was able to successfully adapt to this world. This transition is still in progress 25 years later.

I’m not sure I realized these parallels reading Hemingway and Remarque back then, but it probably doesn’t matter. I was magnetized by these books anyway.

## Second transition

Around 2010 several things happened. First, I've read enough of Hemingway and Remarque and I didn't know what to read next. Second, I left Ukraine and my access to physical books in Ukrainian and Russian languages was limited. At that time I was reading technical books in English but I have never read a full fiction book in my non-native language. Next few years were periods of struggle with both finding books I would want to read and starting reading books in English. Only around 2014, I was comfortable enough with reading books in English. And only in 2016 I discovered a lot of books that I was excited to read.

In January 2016 I listened to 4 podcasts (2 with Naval Ravikant and 2 with Derek Sivers) (1, 2, 3, 4) on Tim Ferriss show that provided me with 1) some ideas how I can change my reading habits, 2) list of books that were interesting to me.

## Ideas

Here is the list of tips from Naval that I tried and that worked for me:

 - do not be afraid to quit book if you don't like it. Close it and start another one. Maybe you would be able to come back to it some time later (in a month, year, decade) or maybe it's just not your book. Don't feel guilty about not finishing it
 - start several books simultaneously. Pick up 2-5 books at the same time and see which one you like the most and continue with it. Come back to other books later. This one works great with the first tip
 - always have several books available to be started. Either maintain library at home with some pipeline of books or if you use Kindle buy several books even if you are not going to start them next week. Maintain pipeline. Tip 1 and 2 depend on this.

Derek Sivers shared his great idea of keeping down notes of books he has read. I thought that idea was great but too difficult and time-consuming. But we will come back to this idea later.

From my personal experience changing styles of books you are reading also helps. E.x. if you are reading 3 books in a row about spirituality that might become boring. Mix and match books, read a fiction book and then non-fiction, change topics etc. It happened to me at least once during the year one book reminded me so much of the previous one that I just stopped reading it (however I plan to come back to it later).

## New problems

This year is already one of the best in terms of reading for me personally. I don't think I've read that much since middle school. However 10 months after starting reading again I noticed several new problems.

I've read several books that I was super excited after finishing. Books like Sapiens, Bruce Lee Striking Thoughts, Bertrand Russell's Best, Ill Fares the Land and few others impressed me a lot, they presented some new ideas I didn't know, some wisdom, approaches etc. They triggered a lot of thought. I was very enthusiastic after each of them but the problem is few month later I couldn't remember a single idea of any of those books. I don't know what I liked about "Sapiens" book, I don't remember what Bruce Lee's insight I liked. The only thing I remember is whether I liked the book or not. I remember my feelings about the book, not the ideas presented in it.

I recently finished reading two books that go well together: Brave New World by Aldous Huxley and Amusing Ourselves to Death by Neil Postman. This is truly the most powerful pair of books I've read in years. After finishing those two books I've got scared that in 3 months I would forget what I liked about them and what were the ideas of those books. And I don't want to forget. Those books contain ideas of high importance. The same is true about books I enumerated above.

So what should I do?

## New solutions

I started thinking in the last couple of days about the problem of forgetting. And I think there are at least several points to be made here.

Most of the worthy books were written not for entertainment. That stands true for both fiction and non-fiction. Everything worthy requires time, commitment and effort. It seems that effort just to read a book is not enough.

In a school for every worthy book, there was dedicated time for at least several lessons. During this time, you would have discussions about the book, discussion about the context in which the book was written (historical time and author biography e.x.), you would write some essay with critique about the book, you would have to test comprehension. You would basically think about the book and repeat it's message in different mediums on the different days. This reminds me of Spaced Repetition technique. You are repeating what you've learned over the period of time and you combine mediums too. At the end, a lot of information about the book is engraved in your brain. It would be much harder to forget those ideas, because you not only read them but discussed them, argued about them, wrote about them etc.

Alain de Botton once presented the idea of the importance of repetition. He argued that the brilliance of traditional religions is in the constant repetition of the truths and values. E.x. you go to church and listen to the same stories every week. I think that is what we are missing now. We should concentrate on the quality of knowledge/information/ideas/wisdom we consume.

It seems that fiction is much easier to remember than non-fiction. Fiction is more visual and easy to grasp. I can recall a plot of a lot of fiction books I've read. As I said I can't do that for non-fiction. The reason for that I think lies in the nature of non-fiction books. Non-fiction books are about ideas. Ideas are abstract concepts. They are not always directly tied to reality. In order to remember such book later, you need to understand it very well. In order to understand non-fiction book you've need to build mental model of this book in your head. Non-fiction authors have a mental model of the world in their heads when they write a book.Your goal is to rebuild that model in your head, to make it physical. Non-fiction sounds a little bit like programming. The code is an abstract expression of author ideas about the world. Your goal is to grasp it now and make it possible to recall in the future.

Thinking of this difference between fiction and non-fiction I realized that Alain de Botton's The Course of Love written in a most brilliant way. It's written like a novel (fiction) but it has quotes of his main ideas in each chapter (non-fictional ideas in a non-fictional style). Those quotes are important there because sometimes it's not always easy for you to formulate idea nicely even after reading the story. I wonder if there are other books like that? That is an interesting approach for modern journalists, philosophers to take: pick your serious topic and present it in a fictional way but express and highlight your main ideas directly.

Another good idea is to read books in pairs. I mentioned before Brave New World and Amusing Ourselves to Death. These two books work great together. It's much more difficult to extract true value of Brave New World by yourself. E.x. for me world described by Huxley was scaring but I couldn't formulate all the reasons why it was that way. Postman gives you good explanations why. He gives also real examples from moderns times that you can grasp more easily.

So it seems that there are possible solutions to the problem of forgetting. It seems that sometimes we can make a process of remembering easier. But I don't think that this is the main takeaway. I think the best thing we can do is to invest more time and effort into reading.

Personally I plan to alter my approach to reading in the following way:

 - use a physical notebook and keep notes while reading a book (we are finally back to the Derek Sivers advice from above). This will slow down the process a lot and will shift focus from reading as entertainment to reading as something more serious (this was one of the important questions by Neil Postman in Amusing Ourselves to Death, should education be entertaining? It wasn't before)
 - after finishing book manually digitize your notes by typing them
 - pick up some question and write an essay about the book (not a short review)
 - find a book club where you can discuss your book and discuss it with people. Giving 1 min summary of a book for people who never read it might be very useful for you

Theoretically, there can be also the technological solution for this problem. It might be something like an online non-traditional book club that would be similar to a school classroom I described above. You will become part of the classroom with other people who are reading the same book right now and willing to join. The classroom would include several discussion sessions and writing essays and tests.

However, I'm not super optimistic about such technological solution at this point of time. There are a lot of open questions. E.x. Is learning more social or individual activity (does the answer depend on a type of personality)? Is it better to have a solution that satisfies fewer requirements but offline (think book club) or online one that is theoretically more feature-complete?

So I'm sticking with my experimental ideas presented above. At the end, I would definitely read fewer books but hopefully, I would understand and remember each of them better.
