---
title: "On space exploration"
url: "/on_space_exploration"
aliases: ["/on-space-exploration-yj74lwymmg9"]
description: "Exploring space exploration"
date: 2016-12-26
draft: false
acknowledgement: 
tags: ["space", "society", "myths", "narrative", "Mars"]
people: []
places: []
locations: []
---

= On space exploration
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-28
:docdate: 2017-12-28
:nofooter:
:document_type: writing
:tags: "space, society, myths, narrative, Mars"

A lot of people get excited about advances in the space exploration in recent years. SpaceX, Blue Origin, NASA missions are all over the news. Discussing the space is fashionable again, space companies get a lot of highly-motivated engineers who want to work for them. All this is obviously not bad, but, in my opinion, space exploration is not the most difficult problem humanity faces, and definitely not the most important one.

Let me make a strong claim. In my opinion, working on space exploration right now causes more harm than provides benefits. It requires a lot of resources (human, financial, maybe energy), and we take them away from other more important areas by using these resources on space programs.

I have heard a lot of reasons why we need to work on space:

we (humans) are explorers, and that is just what we do. To me it seems not enough to answer why we need to do it now.
we can scientifically prove that religions are wrong. To me it seems that this was already done some time ago. World religions have been in decline for the last 500 years.
we need to prove that we are not the only one civilization in the Universe. This requires two questions: 1) why do we need to have 100% scientific proof of it; 2) what will change of we have one? Can't we already assume with a very high probability that other civilizations exist given the size of the universe?
we need to colonize another planet in case something happens to ours. This point seems valid to me. But this brings me to the initial point that space exploration is not a high priority task. What are the chances that humanity would disappear in the next 100 years because of some asteroid hit the Earth vs humanity would disappear because of terminal nuclear war or climate change - issues we are responsible for. It seems to me that latter is way more probable outcome and we should allocate our resources and work on these problems. In a nutshell, we need to make sure that this planet is in a good shape and all humans can live here for at least couple of centuries (if not millenniums) more.
Another point that I was making is that space exploration is not the most difficult problem we are facing. Why would I say that? There is a saying in which your compare simpler problems to a rocket science. "It is not a rocket science", they say. But to me it looks like rocket science isn’t the most difficult problem. It is resource-incentive, though - the more resources you put, the more results you get. At this point it scales pretty well linearly. In my opinion, it is moderately easy, because it is a "pure science". Scientific questions are well understood and are well isolated from complexities of other systems. Rocket science lives on the intersection of other "pure sciences", like physics, astronomy, math etc.

In my opinion the most difficult problems are those that require different bodies of knowledge to solve them, and such problems truly exist in a complex, highly tangled and interconnected systems.

One example of such problem is, of course, global warming. There is no pure technological or "scientific" solution to it. The real solution requires political, economic, cultural, and technological changes. Same is true for poverty, peace, inequality, education, unemployment etc. Those are the problems that are truly difficult and which are very hard to solve at the modern, that is, global scale. Those are the areas where we need research, human, financial and other resources.

To my mind space exploration is easy because it deals with data. What do missions do? They collect photos, samples of minerals - that is raw data. It is easy to work with data. True knowledge and wisdom are not required for it. It's like playing a game at the beginners level, while there are 5 extra exponentially more complex levels.

My final question is why do we need to make colonies now? We don't have a proper answer how to run them yet, what political, economic and social system to setup there? I assume we don't want to copy the model of the Western world with wild capitalism and extreme spending on defense. Why then bother going to Mars, unless we want to make interplanetary wars a reality very soon.

I think we should try to design new better systems here first. New planet settlement sounds great if we could have a healthy and happy society over there. But to build it there we first need to try to do it here, or at least try to develop ideas first.

Philosophy, psychology, sociology, politology, economics, ecology are not the rocket sciences. They are much more difficult because they do not work or exist in isolation. They exist in the complexity of our everyday life and of our societies. Truly difficult problems are here. And are we up to the real challenge?

P.S. I wrote this essay before I read Joseph Campbell's essay "The Moon Walk - the Outward Journey". I'm not incorporating any changes to my essay yet based on his work. I do like his view of the importance of space exploration to humanity. In his mind, space exploration would allow us to have new Myths, that we so deeply in need of. However, I still have to think about his opinion. It made sense to me, but he lived in a very different time from our own. He lived in a time of first trips to space, constant improvement, enrichment of middle class, huge positive social changes after the WWII. We live in a time when the level of optimism about future is quite different from that of 50 years ago.
