---
title: "Overcoming my prejudices"
url: "/overcoming_my_prejudices"
aliases: []
description: "Learning my lessons. One lesson at a time"
date: 2018-01-17
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["life", "life lessons", "prejudice", "universe"]
people: []
places: ["Kyiv", "Ukraine"]
locations: ["San Francisco"]
---

= Overcoming my prejudices
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-17
:docdate: 2018-01-17

November 2017. I'm in the JFK airport, boarding a plane to Ukraine.
My place is in the last row; I notice my neighbor well in advance. 
She is senior American women in her late 70s. 
"Why I never get young and nice people as my neighbors on the plane so I can talk to them and make friends" - 
is the thought that pops into my head. Not very nice of me, I already made my judgments on a person I never met.

Of course, what happened next is precisely the thing you would expect from the universe. 
Simple lesson, straight to the point.
It was the best conversation on the plane I ever had. 
My neighbor shared the beautiful story of her life, her life in Italy and Tunis and then back to the US. 
I learned about her life choices, about her generation and her granddaughter's one. 
I learned about the 60s, how airplanes stayed pretty much the same. She was very curious about my destiny, my beliefs.

She felt very genuine, warm, wise - she was humane. 
I made a mistake of judging a person without knowing her and luckily was immediately corrected.
You'd think I learn my lesson. Far from it.

One week later. I'm in Kyiv. I want to do a manicure in the beauty salon. 
I have an appointment. 
I enter the room expecting to see a good-looking woman, of my age. 
I want to know what Ukrainian women of my generation think about. 
And of course, since I'm in the beauty salon, I expect everyone to be good-looking. 
Shame on me for such thoughts. My master shows up. 
She is in her late forties, slightly overweight women. 
I'm disappointed (shame on me again), my expectations failed me. 

But universe wouldn't give up and provide me the same lesson again. 
The woman was the best person I've met on that trip. She surprised me in so many aspects.
She got her first education in shipbuilding and worked at the factory; 
then she got a degree in economics. 
Eventually, she realized that she didn't like it and started doing nails for people. 
She worked at the beauty salon, and she loved her job a lot (very uncommon for a lot of Ukrainians that I know and who are older than 30). 
At her free time, she painted. 
And her dream was to open small gallery to support and promote young Ukrainian painters.
She was very optimistic, despite living through hard times. 
She was well-read and wise. 
She was very interested in sharing her thoughts and lessons and hearing mine. 
She was about doing what she liked, loving her family, helping people and enjoying her life. 
She felt complete and whole to me. After one hour we felt like good friends. 
She gave me a bit more belief in people, future, and my country, 
and I think I gave that to her too.

Where all these thoughts and judgments come from? 
Why I'm so close-minded at times, and why do I have those stupid beliefs and expectations? 
What are the reasons for it? Is it just me? How do I fix it?

Hopefully, I learned my lesson, and maybe I'll be a wiser person. 
At least in more situations than before.
