---
title: "People I am afraid of"
url: "/people_i_am_afraid_of"
aliases: []
description: "On people that on my opinion are the most dangerous for the society"
date: 2016-02-24
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["society", "modernity"]
people: []
places: []
locations: ["San Francisco"]
---

= People I am afraid of
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-01-09
:docdate: 2018-01-09

There are two types of people that I am afraid of: 

 - people who have one dimension of their personality or skill set and want or already have power 
 - people who are "successful" in one field but don't have feedback loops

There is an intersection between those two categories which we should be aware of. 
Let me explain whom I consider being such people categories and why I am afraid of them.

In the last couple of years, I met a decent amount of people that lead me to write this post. 
For me, those were usually "entrepreneurs" (from various countries) that had 1 goal (become rich and powerful). 
Usually, they also do some projects that bring either ~0 value to people and societies or in some cases creates harm 
(e.x. products that play on weaknesses of people, products that make people worth and not better human beings).

I call these people one-dimensional humans. There is nothing more to their personality than I outlined in the single paragraph above. 
They have a single goal, they are not aware of more complex systems we live in, 
they don't have appropriate knowledge (or education) and interest in the humanitarian sciences. 
The real danger comes not from the fact that those people are one-dimensional 
(because there are a lot of people like that, but they are not dangerous but useful to the societies) 
but from the fact that those types of people have a high chance for "success" in the Western societies. 
And this "success" means money and power. So the real problem arises when people with no real perspective, with a narrow operational mindset, get power. 
Such situation puts the rest of the society in danger, because of the extremely poor choices such people are making.

My dream for us is to consider such individuals not as "successes" but as failures of the society. 
They are products of our past mistakes. Such people shouldn't be celebrated in any way, and they should be kept as far as possible from power.

Those people can be brilliant in their one thing, but they are usually sneaky and easily recognizable within few minutes of the conversation.

Another highly related group of people that I noticed recently are "smart" opinionated people with no feedback loops. 
I like when a person is opinionated, I think it's a good trait, it means to me that person thought about that particular problem. 
What I don't like when a person has an opinion but has basically no mechanism to change that opinion though communication with another person. 
Those people can look smart but to be honest, I wouldn't call any person without feedback mechanism smart (hence the quotes "smart" above). 
Again, there is no real danger until such person achieves some "success" and gets some money and some power. 
After that happens real problems arise. Recently I saw a lot of people who _have all the answers to all the problems). 
I noticed a lot of arrogance and unwillingness to listen, to explain, to discuss, to communicate and to find solutions together. 
Journalists are "experts" on every topic, politicians are "experts," regular people are "experts," "entrepreneurs" are experts on the politics, peace, economy, happiness, etc. 
The list goes on and on. A lot of people right now have opinions that hard to change.


Are we living in the meritocratic society? 
If the answer is "yes", then, in my opinion, we need to change the merits we evaluate "success" on. 
In the long run (for humanity) it's a better decision to not put "bad" people on top. 
People with limited perspective and people with no ability to improve their own point of view causing us a lot of harm. 
Let's evaluate people not by the size of their bank account or how much power they have, 
let's celebrate people who contribute most to the society now and in the long term in proportion to their original resources. 
As I said some people become rich and powerful creating the negative impact on the societies, nature, and humanity. 
And some people are just working hard, making the difference every day in their local communities. 
Let's celebrate the second group of people and let's be aware of the first one. 
Let's shame them, let's not become like them and let's fix the problem that put such people in charge.
