---
title: "Phoneless"
url: "/phoneless"
aliases: ["/phoneless-m48kmx3778k"]
description: "On living a life without a smart phone in the modern society"
date: 2015-09-27
draft: false
acknowledgement: 
tags: ["phones", "consumerism", "anxiety"]
people: []
places: []
locations: ["St. Louis, USA"]
---

= Phoneless
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-28
:docdate: 2017-12-28
:nofooter:
:document_type: writing
:tags: "phones, consumerism, anxiety"

I often get asked why I don't have a smartphone. Interestingly, it's not that easy to answer this question in one sentence. There are multiple reasons and those reasons change over time. Actually they don't change, they grow over the time.

I've got my first and only smartphone in January 2012 when I first came to the US. I've used it every day: checked the news, emails, Twitter and navigated using Google Maps. In June 2012, I left Bay Area and started traveling around Balkans and then South and Central America. Suddenly, having that phone became a chore. I think it was locked and I couldn't use it properly in different countries. But that wasn't a point. Frankly, I don't think I needed it that much. So I didn't have smartphone ever since summer of 2012 (I've got a regular basic phone without the Internet just 1 month ago for my work). I don't think it was conscious decision back at 2012, however not getting a smartphone ever since was a conscious one since I thought about it a lot in the next years.

I remember in 2012 I noticed that I lost my ability to listen to a person for more than 3-5 minutes. Basically, I wasn't able to concentrate on one topic and one person. While listening to the person, I was thinking about something completely different in the background. That was really awkward and embarrassing. I wasn't able to follow up with good questions to continue a conversation. If you are not interested in what person is saying to you, I doubt she will be interested in listening you too. I think that was completely new issue for me that appeared while I was using smartphone and was online all the time. I didn't like those changes to my mind and my personality. I do believe that technology should assist us in becoming better versions of ourselves, opposite direction is not appropriate.

The Internet is the big source of knowledge but also a huge source of distraction. I do feel that our generation is probably the most consumerist of all of them. It became too easy to consume news, shows, movies, music videos, stuck in different forums, chats etc. We often made fun of our parents who constantly consume TV with stupid shows and one-sided news. But I think newer generations are actually worst in this respect. Everyone is connected to the Internet 24 hours every day. Nowadays consumption happens not only during newspapers reads and evening news shows, it happens every 10 minutes when we refresh our Facebook/Twitter feeds, check our instagrams and snapchats. I think that consumption is the biggest enemy of production and creativity. It's like a path of the least resistance. It's very tempting to consume something and it's much harder to create. The most worrying thing for me is the constant consumption of thoughts and opinions. I feel if you delegate function to get thoughts and opinions to the somebody/something you lose the ability to create them yourself. Our brains need practice!

If you are working in any creative field getting into "the flow" is your ultimate goal. It's something almost mythical that you can achieve only rarely and something you don't understand until you experience it. In my opinion, one of the preconditions for getting into the flow is getting long spans of time without interactions. E.x. you can't be in the flow if someone would come to your table every 5 minutes while you working. For doing creative work we want quite spaces. But I don't think it's possible to avoid interruptions if you connected to your phone, your smart watch etc. Your are constantly bombarded by new emails, private message, public chat messages, notifications from apps etc. I don't think most of us have even 30 straight quite minutes during our work days.

I also think that having 24-hours access to the Internet raises our anxiety levels. Our parents watch this depressing local and international news and worry a lot about things they have no influence on. We however also worried about news. But they are news about our Facebook friends, they are news about some events that are happening now. And we have strong fears and anxieties to miss these events. The problem is that we not worried to miss something once per week or per day, but every 10 minutes. We want to know about those events in the realtime. So basically every minute of our life we are anxious about some issues. Not a great place to be. I strongly recommend to watch Alain de Bottom talks on news and anxiety.

Personally, it was much harder for me to be at the moment when I had a smartphone. It was extremely difficult to have a meaningful conversation, it was hard to keep any conversation with someone at all because any second me or person I was talking with would pull up phone and check something.

Camera in our mobile devices has another weird side-effect on our comprehension of the world. If you have a camera always with you then you'll try to use it. Suddenly everyone became a photographer. Instead of just enjoying the beauty of the nature or amazing energy of some music band people would make photos or videos. Instead of looking on the world through the open eyes they start looking into it through the phone screen. There are people who enjoy photography and I understand when they are taking photos, but not all of us are photographers, right?

I'm not against smartphones or other Internet-connected devices. They provide us with some very useful functionality. Everyone has their reasons for having a phone. My goal is to understand the trade-offs - what I'm personally getting and losing owning a smart phone. And my only wish is that everyone was able to evaluate personal trade-offs themselves and made an educated decision.

For me the decision was down to evaluating whether constant interruptions and higher anxiety were worth the convenience of getting access to Maps and Wikipedia all the time.

As a software engineer, I'm connected to the Internet probably 14 hours every day. I consume huge amounts of information during those hours. Not having a smartphone gives me ability to be offline for the short periods when I'm commuting, or doing shopping or walking, or having a meal in the restaurant. I think we should strive for the balance and to have some time for ourselves. It can be scary at the beginning and maybe even boring. But that is the only way to know who you are and who you want to be. Permanent consumption prevents us not only from creating products but from knowing and improving ourselves.
