---
title: "Reduction"
url: "/reduction"
aliases: []
description: "Reducing ourselves"
date: 2017-12-29
draft: true
acknowledgement: 
categories: ["Writings"]
tags: []
people: []
places: []
locations: []
---

= Reduction
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-29
:docdate: 2017-12-29
:nofooter:
:document_type: writing
:tags: ""

We reduce people around us.
How often do we forget _all_ the good things about someone and focus on their "faults" at worst or few "positive" things at best?
When we forget to acknowledge good things about other people we create problems for ourselves and other people.

What kind of problems, you ask?

When you tell someone (your child, your friend, your partner) that they are good at this _one_ thing they might start to 
doubt their wholeness - they might doubt that they have other "good" traits or even doubt that they are able to 
have them in the future.

So such reduction, affects your perception of another person, 
it might affect self-perception of that person, and it will damage your relationships too. 

Let's be careful with each other. Let's try to not project our insecurities on other people. 
Let's be explicit about all (even tiny) things we appreciate in each other. 
And also let's be conscious and mindful of those good things.

Maybe our kind words can change someone's life. 
Maybe we will bring a smile on someone face, or a tear of sadness followed by a tear of relief and happiness. 
Perhaps we will lift someone out of depression or difficult stage of life.

Let's not do assumptions about other people. Let's be kind and gentle with each other.
