---
title: "sensless_smells"
url: "/sensless_smells"
aliases: []
description: "Smells of Ukraine"
date: 2018-05-01
lastmod: 2018-12-13
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["smells", "scents", "Ukraine"]
people: []
places: ["Ukraine"]
locations: ["Berlin-San Francisco"]
---

= Sensless smeels
Anton Podviaznikov <anton@podviaznikov.com>

On my recent trip to Ukraine I discovered how my senses can be 
constantly bombarded with new stimuli.
Stimuli distract us, take us from inside ourselves into the outer world.
Sometimes they also bring memories, make us more aware of surrondings.


*cigarettes*
I can smell them on the streets. Either from people I don't know 
or whom I hug.

*toilet air purifiers* 
Being in a restaurant I would go to a bathroom and have a
flashback from the past. Still the same, highly checmical, direct, powerfull, non-organic, unpleasant smell. 
Smell that is forever associated in my mind with Ukrainian toilets.

*petroleum*
I am in the taxi, making my way through the traffic. I open the window in the car.
Smell of the pretroleum. It's my face. It's everywhere. It comes inside my cra.
Everyone still have this old non-environmental friendly car.
It's a smell of a poor country I grow up 20 years ago.

*laundry detergent*
I am staying at the city for a few days now. I want to do my laundry.
I buy local detergent. My clothes are clean now. But there is a problem.
They smell now. They covered with unpleasant, not natural artificial smell.
I try to get rid of this smell by rinsing my stuff over and over again.
It's impossible. It's stuck. Same scent as 2 decades ago.
Now I'm bound to wear it for the rest of my stay. I wear my memories now on me.

*beer*
Ukrainian beer is different. Bad taste, bad smell. I inhale it, it brought me back in time.
I remember now again why I don't like it and didn't miss it.

Scents are everywhere. They have a power to bring us back in time.
For the better or worse. They can make us nostalgic or happy for a moment.
But important part is that they cannot make us present in a sense.
They make us feel something but also to reflect on our tastes, our values and even lives.
They are tools of time travel, they trigger in us contact with something important, 
but if they are unpleasant they took us out from the flow, 
from this particular moment.