---
title: "Slavic Hospitality"
url: "/slavic_hospitality"
aliases: []
description: "Explaining Slavic Hospitality"
date: 2018-08-12
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["generalization", "Slavic", "hospitality"]
people: []
places: ["Kyiv", "Ukraine", "New York City"]
locations: ["Kyiv"]
---

= Slavic Hospitality
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-10-30
:docdate: 2018-08-12
:nofooter:
:document_type: writing
:tags: "generalization, Slavic, hospitality"

One of my favorite restaurants in the New York City is a place close to East Village that 
serves Balkan food. It is called _Kafana_.

I've spent 1.5 years living and working in Montenegro, traveled to most of the countries 
in the region multiple times. That region is my second home.
That is why _Kafana_ is a place I always try to attend while in NYC.

I like reading their menu, I love hearing Serbian or Croatian language at that place.

During one of my previous visits, I finally became aware of the following phenomena.

I was sitting in _Kafana_ and observing new guests coming.
Owner - middle-aged man from Balkans - would be very grumpy, not smiling with his foreign guests.
You'll get the vibe that they are not welcomed, and he actually doesn't care if they are here or not.
Or you might think that he is in a bad mood today.

But then suddenly came a group of people who he knew. Everything changed, he was welcoming, laughing,
spending time with them at their table, sharing news, etc.
He transformed in the most welcoming and happy person who really happy to feed these people and talk to them.


At that moment I realized - this is just generalization - that is how Slavic hospitality looks like.
You are grumpy and unwelcoming and uncaring towards strangers, and you are the most welcoming person 
towards _people you know_.

Since I became aware of this idea, it became more comfortable for me to travel to Eastern Europe myself.
I see the same thing happening in Ukraine over and over again.
As I said, my explanation is just a generalization, this thing happens not in all the cases.
From my Ukrainian experience, I can say that maybe in 50% of coffee shops I might experience
grumpiness, but this number shrinks rapidly every year.
People in the coffee shops and restaurants are becoming more and more welcoming and smiling. 
And this is the change I definitely welcome.
