---
title: "Soviet Union 2.0"
url: "/soviet_union_2_0"
aliases: ["/soviet-union-20-012lo0g230n"]
description: "On similarities between modern world and Soviet Union 30-40 years ago"
date: 2017-03-05
lastmod: 2018-12-13
draft: false
acknowledgement: 
tags: ["modernity"]
people: []
places: []
locations: ["San Francisco"]
---

= Soviet Union 2.0
Anton Podviaznikov <anton@podviaznikov.com>

The modern globalized world looks surprisingly similar to the Soviet Union in 1970-1980s.

That might sound very contrarian, but I will try to explain what I mean using few examples.

The Soviet Union was pretty much _monocultural_ country. I mean that in two senses.

Firstly, it was Russian-language dominated culture. 
The rest of the nations and cultures were slowly moving into using the Russian language and melting with the Russian culture. 
I believe that the same is happening right now on the global scale. 
Afterward, it's the whole premise of globalization. 
All the countries and cultures are melting into the Western civilization and English as a language becomes more and more dominant.

Secondly, all the concepts of the shared culture were produced in few cultural centers and distributed in a centralized manner. 
The same is happening right now. 
We watch movies produced just in few places (mostly Hollywood).
We listen to the music produced by few producers. 
The culture is mostly English-speaking nowadays, and people across continents 
can relate to each other because of the same content they consume.

In the Soviet Union, all the _shops_ looked the same across the country. 
E.x. all the malls looked similar and were selling same goods, 
restaurants and cafes looked the same and had a similar menu, 
press kiosks looked the same and were selling the same newspapers and magazines across the country. 
The same thing is happening right now. 
You can find starbucks, mccdonalds, h&ms, zaras in the majority of the countries on this planet. 
You fly into some country, arrive at the airport that looks like any other airport and has all the same shops that 
sell the same brands and labels. 
Downtowns across different cities look the same with the same cinemas (that have same movies), 
same boutiques and mass-market clothing brands and same restaurants.

The modern globalized world has _limited political variety_. 
You may say that it's not true and that Soviet Union had only one party. 
But I would argue that there was always the opposition to the Communist Party. 
There were dissidents who provided another view/perspective. 
That is quite similar to the majority of the Western countries that had two parties for decades now. 
Two main parties that always win the election is not variety. 
Such setup doesn't provide plurality and ability to explain and solve problems in such a complex world we live in.

_Belief_. In the Soviet Union, there was a belief in planned, centrally controlled economy. 
Similar belief exists in the modern world, where everything can be explained and solved by the free market. 
Both systems believe in the human-made idea and bet heavily on it without any questioning.

_Normalization_. The Soviet Union tried to make everyone to be the same. 
People had similar clothing, similar haircuts, same education, same holidays. 
The same is happening now. 
People have same phones, play same games, watch same movies, get same news, 
wear few clothing labels and even have same haircuts (decided by what is particularly popular at this very moment). 
With all the theoretical variety capitalism provides, 
the system still produces very similar human beings (it might be two big groups in some rare cases, but that is still not a wide variety).

_No belief in the future_. In the Soviet Union, by the late 1970s, no one believed in the achievement of Communism 
that was promised in the 1960s. 
The dream became unreal and people saw that it's not achievable. I think, our modern world stuck with the same problem now. What is our current dream as a society or as a species? Do we have some common goal or story?

_Useless media_. Media was useless and untrustworthy in the Soviet Union, especially regarding international matters. 
However, the same is true regarding mainstream media in the modern world. 
You can't trust media because they represent private economic and political interests.

_Inequality_. The Soviet Union had two classes of people: the ruling class - "nomenklatura", 
and the working class - ordinary people. 
The difference in quality of life between those two classes was incredible. 
However, in the modern world this problem even more visible. 
The elites are getting unproportionally better of every day.

_National inequality_. The Soviet Union had the title nation, 
few "second-sort" nations and the rest was "third-sort" nations. 
The same is true for the globalized world. 
Some countries that are getting better in the existing system and countries that get exploited.

The _decline of spirituality_. The Soviet Union from the very beginning was against organized religion. 
However that also led to the decline of spirituality which is very different thing from the religion.
The same thing is happening now everywhere.

_Addictions_. The Soviet Union used to have epidemic of alcoholism 
(which state even tried to fight in the 1980s with the alcohol ban). 
But in the modern countries, we have epidemic of obesity and entertainment 
(in the form of television, Internet, games, etc). 
Both have the same reasons. 
Such epidemics happen when there is some disconnect between a human being and the world. 
And the result is the same: damaged body, mind, and soul.

_Architecture_. The Soviet Union is famous for its tasteless architecture style and buildings that look all the same. 
However, I do believe that it's true with modern architecture as well. 
As I mentioned before all airports look the same, skyscrapers are ugly and look the same, 
same is true for residential buildings. 
Probably 90% of new buildings are tasteless.

_Street look_. In the Soviet Union, a lot of propaganda posters were outside on the buildings and streets. 
They had no taste and no real value. 
Modern cities of today are covered with ads, which is a very similar thing - sell us ideas we didn't ask for.

_Imaginary enemies_. In the Soviet Union, there was the idea of "enemies,"  
that at that time were outsiders and some groups of people inside the country. 
Those "enemies" allowed the country to live in the constant threat. 
Same is true about the modern world. 
There are constant threats from "terrorist", new viruses, some "aggressive" nations, etc.

_Food_. There wasn't a wide variety of food in the Soviet Union. 
Even fruits and vegetables didn't vary that much (which can be explained by geography). 
However, I feel that the same is true with food in modern chains. 
All apples or bananas look and taste the same.

_Dogma_. In the Soviet Union, it was dangerous to "think" and to talk about ideas. 
In the modern society, it's not prohibited, but people don't do it anyway. 
People are afraid to explore ideas, they would rather stick to something they heard before, 
or they would be in a defensive mode to "protect" their preconceived ideas. 
Exploration mode is very rare these days.

_Incarceration_. The Soviet Union was famous for having prisons and putting large numbers of people there. 
However the same applies to some modern Western countries. 
Now almost 1% of US population is in the prisons.

_Antidemocracy_. Elections in the Soviet Union didn't depend on the popular vote in reality. 
People did vote, but results were predefined, because only one party were eligible for election. 
A lot of modern countries have same problems, the results of elections are also predetermined. 
They usually depend on the amount of funding for the poltical campaign. 
So formally, people do vote (as in the Soviet Union), but in reality, the results are known in advance.

_Power centers_. In the Soviet Union power belonged to the people who were not elected and got the mandate from the population. 
In the modern Western countries that it is also true. 
The real power belongs to the bankers, financiers, heads of corporations - people who didn't participate in any elections.

In my opinion, the lack of variability was one of the major critics of the Soviet Union.
However, I can say the same thing about the modern world. 
Sure, you can have variety, if you have enough financial resources, 
but the same was true in the Soviet Union, 
where the ruling class could get anything they wanted.

I tried to draw some analogies between the Soviet Union 30-40 years ago and the modern world. 
Maybe I made some factual mistakes, maybe my analogies are too stretched out, 
but it's up to you to decide. 
Anyway, I think it's a useful exercise to think what did happen to the world in the last 30-40 years, 
what changes were positive and what were negative.

