---
title: "The Age of Constructive Conversation"
url: "/the_age_of_constructive_conversation"
aliases: []
description: 
date: 0-00-00
lastmod: 2018-02-26
draft: true
acknowledgement: 
categories: ["Writings"]
tags: []
people: []
places: []
locations: []
---

= The Age of Constructive Conversation
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2018-02-26
:docdate: 2018-02-26
:nofooter:
:document_type: writing
:tags: ""

A couple of weeks ago I was ill at home. 
As I had some spare time, I spent some of it reading Twitter. 
That was the week of few sexual scandals. One involved American comic Aziz Ansari and another one involved Woody Allen.
I couldn't read too much of the comments because it was too depressing. 
But the general feeling I've got that audience split into two camps: the difference was only whose side each party supported.

Later I had the same type of conversation replicated in the offline setting.

Few things disturb me in what I've noticed:

 - as I said, there are always _two_ camps. And discussed issue  used for polarization and delaminating line of the conflict
 - the discussion is mostly emotional and not rational. It's usually about expressing emotions and fears, but not understanding what happened
 - the discussion is mostly about individual people and blame. The blame would be assigned to the discussed individuals, and no effort would be made to identify underlying structural real reasons for the discussed situation
 - the discussion is usually about past and not the future. I've heard a lot of arguments about why some person was wrong. But I never heard ideas or what _to d_o about the issue. What actions each one and all of us should take to solve the problem

There are different functions that conversation perform. 
Informational exchange, emotional exchange, probing of what our peers think and into our "normality." 
What lacks nowadays is the function of knowledge seeking. Engaging in the conversation to not exchange information but to seek knowledge and to generate it.

Wouldn't it be great if we approach conversation willing to learn something new, change our opinions, 
find underlying reasons for issues, find underlying relationships between different notions and at the end generate some ideas how to solve the problem.

Let's go back to the Aziz-Grace story. 
Do we need really to blame _one person_ in the story? 
Let's assume that you took an easy route and decided that the only person who made a mistake is Aziz. 
You can spend all your energy (which would be mostly hatred - negative type of energy) explaining why he is wrong.
However, even with simple analysis, you might see that both parties had a bad experience 
(to a different degree of course, but this situation is not a win-lose situation, both parties were losers).
A bit later, you realized, that _both parties_ had opportunities to stop the escalation of the situation into the problem and _both parties_ failed at that.
For a conflict between individuals to happen there should be two people involved. 
That is a simple insight that gives some hint about how to solve the given problem.
A bit later, you might realize, that this story is not about Aziz and Grace at all and that this situation happens in all type of relationships 
(and not exclusively romantic one). 
From the higher level of view, it seems to be a problem of communication between two individuals in general.
Then you might think who is _really_ guilty in this situation. 
Was this result of the pure failure of Aziz, or Grace, or both? But aren't they also the products of their societies and their culture.

Kahil Gibran wrote in The Prophet:

> Oftentimes have I heard you speak of one who commits a wrong as though he were not one of you, but a stranger unto you and an intruder upon your world. 
> But I say that even as the holy and the righteous cannot rise beyond the highest which is in each one of you, 
> So the wicked and the weak cannot fall lower than the lowest which is in you also. 
> And as a single leaf turns not yellow but with the silent knowledge of the whole tree, 
> So the wrong-doer cannot do wrong without the hidden will of you all. 

And most importantly you might start thinking how to solve this problem for the majority of people. You want to maximize impact.
If you did recognize, that both parties are losers here, 
if you did recognize, that both suffered,
if you did recognize that this failure was also systematic and cultural failure more than an individual one.

Then you might come up with a list of ideas/directions to work on:
 - how about teaching kids of both sexes to communicate their boundaries better (and maybe even adults)
 - how about teaching some skills of emotional intelligence, like body language
 - how about improving how we teach sexual education
 - how about making pop culture Hollywood movies on such topics, showing what is appropriate and what is not. 
 Why do we have so many movies focusing on having sex on the first date, but no movies that show us how to communicate "no".

And when you realize, that the problem is systematic and that you are part of the problem you become more empathetic. 
And empathy is positive energy. 
The same goes for the producing list of ideas. You've created something new here. 
Congratulation, you switched from the negative hatred to productive and positive creation.



