---
title: "The Best Game"
url: "/the_best_game"
aliases: []
description: "Thinking about the nature of games"
date: 2018-02-09
lastmod: 2019-01-21
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["games", "football", "competition", "collaboration"]
people: []
places: ["São Paulo"]
locations: ["San Diego"]
---

= The Best Game

In January 2013 I was staying for a month in São Paulo, Brazil.
It was during my "digital nomad" stage of life where I traveled slowly and lightly.

While in the city, I decided to join YMCA and play football with local guys. 
I played every morning from 6.30-7.30AM five days per week. 
It was the best football experience of my life.

I'll try to decompose this a bit to understand what made it great.

I'm playing football for well over twenty years now. 
Quite often you are together on the team with the guy who thinks he is much better than everyone else and he would try to dribble past all the opponents and score goal all by himself. 
That would work one or two times per game, but that strategy is not reliable if the opposing team is any good. 
The well-organized side has much higher chances to beat a group of individuals who play all by themselves, even if individually each player on that team is better.

Brazilians played like a unit. A lot of them could easily beat opponents. 
But that is now what they chose. 
They understood the game on a deeper level. 
They knew that it's about collaboration. 
Scoring a goal because of the team effort is also remarkably fulfilling because it connects you with your team-mates.
Suddenly everyone becomes very important to the team. 
Everyone has a role to play and responsibility towards teammates. 
And if you make people _responsible_ for something - they would strive. 
They would try to improve; they would try to do their best and not let their team-mates down. 
They will be on their toes each minute, and they will try to play even better tomorrow. 

Usually, if less skillful people make one or two mistakes, no one would pass a ball to them until the end of the game. 
It is a terrible strategy that I saw too often during my life. 
When you make a mistake, and no one believes in you, then you lose confidence, and you lose motivation, and you more likely to make more mistakes. 
You lose sense and meaning of the game and the time. 
The best way to overcome that is by passing to the person who just made a mistake. 
They will feel trusted. 
And also since you involve them in the game they can improve their skills and make fewer mistakes. 
If you don't play with them - they would never become better. 
So the good teams have mechanisms for developing _all the players_, not just the best ones. 

In just a couple of weeks playing with those guys, 
I became much better player than I ever was. In addition to having more amount fun than ever.

What I learned from this is that:

 - ego is a problem. People who play by themselves usually have a massive ego, and it's not fun to have them around.
 - trust and responsibility are essential. Believe in your teammates and make them responsible for something. It's a win-win.
 - victory as a result of collaboration (or team work) is much more satisfactory than any individual achievement
 - there are different ways to play a game (or live life for that matter), not all of them are equal
 - if fun and happiness are distributed - everyone wins 




