---
title: "Ukraine: Nov 2017"
url: "/ukraine_nov_2017"
aliases: []
description: "Look with the fresh eyes"
date: 2017-12-29
draft: false
acknowledgement: 
categories: ["Writings"]
tags: ["Ukraine"]
people: []
places: []
locations: ["San Francisco"]
---

= Ukraine: Nov 2017
Anton Podviaznikov <anton@podviaznikov.com>
:revdate: 2017-12-30
:docdate: 2017-12-30
:nofooter:
:document_type: writing
:tags: "Ukraine"

In July 2015 I wrote a https://podviaznikov.com/ukraine/[post about Ukraine] that defined two things 
that made me optimistic about Ukrainian future.

At that time for me, it was mostly theoretical exercise and even to some extent an example of wishful thinking.

In Nov 2017 after almost 4 years I visited Ukraine. What I saw _shocked_ me.
I was overwhelmed with emotions, thoughts, ideas.

What exactly did I see?

Downtowns of big cities (Kyiv and Kharkiv) looked completely different.
They were full of modern coffee shops, cafes, restaurants.
They were filled with people (both locals and foreigners).
Those places were modern in all senses:
 - beautiful design - interior and brand - with attention to details
 - young, good-looking, English-speaking, _polite_ and _helpful_ personal. 
 This is a significant point, it wasn’t like that before at all. 
 Only 30 years ago our service industry was full of angry, bitter ladies working for state-owned enterprises
 - modern menu. Ok, when I saw browny,  merengue, marshmallows on the menu in Kharkiv - 
 I was both impressed but also started thinking about the speed of globalization. 
 That menu was no different from the one I see in San Francisco
 - tourist-ready. As I said, personnel could speak English, all the menus had English translations.
Those coffee shops and cafes are examples of small businesses. 
As I argued in 2015, people are not afraid to start their own ventures. 
Small businesses are remarkably important. In my opinion, they drive change. 
They emerge from the bottom and not from the top. 
That is why I don’t care which political party wins elections as long as people continue to take the initiative, start businesses and be active in all other spheres of communal and social life.
The best part that those small businesses look very modern (in the sense that I described above). 
By doing it the right way, they set an example for everyone else. 
The ones that would come after will build on this experience.

In 2015 I wrote, "we started to value intellectuals, it’s becoming fashionable again to be smart and kind."
This thing happened! I’m so excited about it. When I left Ukraine in 2010, it was still cool to be “cool” (in the sense of “bad boys”).
While in Kyiv I saw a tremendous amount of small new libraries or coffee shops/libraries. Young people started were reading good Modern books. I’ve met two software engineers, and how surprised I was when we realized that 3 of us read the same books (e.g., Peter Thiel’s “Zero to One”). And I’ve got many good book recommendations.

At the same time, Kyiv is filled with trivia and quiz nights. I visited one music trivia Wednesday night.
There were like 20 teams with 6 people each trying to beat each other in the knowledge of music bands.
I was told that events of such type are happening almost every night. And there are music, history, sport trivia nights, etc.

In Ukraine 2010, it was cool to drink alcohol and gather with friends at one’s apartment. Now it seems to be cool to do yoga, attend workshops, read books. Street fashion changed too! I’ve met British girl in Kyiv who lived there for 9 months, and she was complaining that Kyiv is even _too_ hipsterish for her. I’d take it as a good sign at this point in time.

Following the leaders. What I also noticed that people started looking abroad for ideas. Coffee shops with Western design are good examples of this point. There is no need to reinvent everything. Take what is working somewhere and use it. I saw the same in conversation with software engineers. They told me how their companies tried to improve themselves by studying books on hiring and managing at Google and other big US companies.

I also noticed how deep technology penetrated society. Middle-aged Ukrainians are using Uber, asking about Bitcoin, buying drones, shopping online and using same-day delivery services.


For me, I practically saw no difference between creative class in San Francisco, Hong Kong, London, and Kyiv.
Forgetting about globalization issue, in general, I consider it a good thing for Ukraine at this particular moment in time.

